services:
  mlgg-frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - RESEND_API_KEY=re_4jWQNBbY_7ywwXumXPN9ibaFCHusgTRiX
    ports:
      - "8581:80"
      - "4247:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
